apiVersion: v1
kind: DeploymentConfig
metadata:
  name: spring-hello
  namespace: {{PROJECT}}
  labels:
    app: spring-hello
spec:
  replicas: 1
  selector:
      app: spring-hello
  template:
    metadata:
      labels:
        app: spring-hello
    spec:
      containers:
      - name: spring-hello
        image: nexus.esc.yipintsoigroup.com/spring-hello:{{TAG_IMAGE}}
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: nexus